# Generated by Django 4.2.13 on 2024-06-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(default='degree', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='members.disciple'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(default=2020, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='members.class'),
        ),
    ]
